name: CI

on: [push, pull_request]

jobs:
  test-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v3
        with: 
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}

      - name: Install nvim plugins
        run: |
          export NVIM_PACKAGE_DIR=$HOME/.local/share/nvim/site/pack/vendor/start
          mkdir -p $NVIM_PACKAGE_DIR
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim $NVIM_PACKAGE_DIR/plenary.nvim
          git clone --depth 1 https://github.com/ipod825/libp.nvim $NVIM_PACKAGE_DIR/libp.nvim
          ln -s $(pwd) $NVIM_PACKAGE_DIR

      - name: Run tests
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64
          git config --global user.name "foo"
          git config --global user.email "foo@bar.com"
          make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check .
